name: Build and Push to ECR

on: [push] # Or any other event that triggers this workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: eu-central-1
  REPOSITORY_NAME: streaming_pipeline
  LOCAL_IMAGE_NAME: streaming_pipeline
  AWS_PROFILE: default

jobs:
  build_and_push:
    runs-on: ubuntu-latest # Choose an appropriate runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create ECR Repository
        id: ecr-repository
        uses: int128/create-ecr-repository-action@v1
        with:
          repository: ${{ env.REPOSITORY_NAME }}

      - name: Build images & push to ECR
        uses: docker/build-push-action@v4
        env:
          COMMIT_TAG: ${{ env.REPO_NAME }}:commit-${{ github.sha }}
          LATEST_TAG: ${{ env.REPO_NAME }}:latest
        with:
          context: .
          file: ./modules/streaming_pipeline/deploy/Dockerfile
          target: release
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.COMMIT_TAG }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.LATEST_TAG }}
          push: true
